# Generated by Django 5.2.1 on 2025-05-28 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.CharField(max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
    ]
