# Generated by Django 5.2.1 on 2025-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='movimiento',
            field=models.CharField(max_length=255),
        ),
    ]
