# Generated by Django 5.2.1 on 2025-05-29 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_bitacora_movimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
