# Generated by Django 5.2.1 on 2025-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_bitacora_options_alter_bitacora_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
